### ISSUE TITLE
Get Ask does not return my asks

### ISSUE THREAD

**Issue by tiviti** [liorshalev01/commons-server#2]
Follow this sequence:
1. http://52.0.221.123:3000/api/v1.0/users/564250433cb8d5aa3b3dc66c/asks
{ 
    "common": "friends",
    "content": "Ilan test bug 1",
    "isAnonymous": "true"
}

2 http://52.0.221.123:3000/api/v1.0/users/564250433cb8d5aa3b3dc66c/asks/followed

I get empty results. The ask in step one should have returned the new ask

**Comment by liorshalev01** [comment]
fixed.
